<?php

class PxlBannerBox_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_banner_box';
    protected $title = 'Case Banner Box';
    protected $icon = 'eicon-posts-ticker';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"section_layout","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/localhost:8000\/wp-content\/themes\/proactive\/elements\/assets\/img\/pxl_banner_box\/layout1.jpg"},"2":{"label":"Layout 2","image":"http:\/\/localhost:8000\/wp-content\/themes\/proactive\/elements\/assets\/img\/pxl_banner_box\/layout2.jpg"}}}]},{"name":"section_content","label":"Content Top","tab":"content","controls":[{"name":"main_img","label":"Main Image","type":"media"},{"name":"secondary_img","label":"Secondary Image","type":"media","condition":{"layout":["1","2"]}},{"name":"title","label":"Title","type":"text","label_block":true,"condition":{"layout":["1"]}},{"name":"number","label":"Number","type":"number","default":100,"condition":{"layout":["1"]}},{"name":"suffix","label":"Number Suffix","type":"text","default":"","condition":{"layout":["1"]}},{"name":"pxl_icon","label":"Icon","type":"icons","fa4compatibility":"icon","condition":{"layout":["2"]}}]},{"name":"section_content_bottom","label":"Content Bottom","tab":"content","condition":{"layout":"1"},"controls":[{"name":"third_img","label":"Image","type":"media"},{"name":"t_title","label":"Title","type":"text","label_block":true},{"name":"t_number","label":"Number","type":"number","default":100},{"name":"t_suffix","label":"Number Suffix","type":"text","default":""}]},{"name":"banner_style","label":"Style","tab":"style","controls":[{"name":"title_color","label":"Title Color","type":"color","selectors":{"{{WRAPPER}} .pxl-banner .pxl-counter--wrap .pxl-counter--title":"color: {{VALUE}};"},"condition":{"layout":["1"]}},{"name":"title_typography","label":"Title Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .pxl-banner .pxl-counter--wrap .pxl-counter--title","condition":{"layout":["1"]}},{"name":"number_color","label":"Number Color","type":"color","selectors":{"{{WRAPPER}} .pxl-banner .pxl-counter--wrap .pxl-counter--number":"color: {{VALUE}};"},"condition":{"layout":["1"]}},{"name":"number_typography","label":"Number Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .pxl-banner .pxl-counter--wrap .pxl-counter--number","condition":{"layout":["1"]}}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'jquery-numerator','pxl-counter','pxl-counter-slide','proactive-counter' );
}